version: '3.8'

services:
  db:
    build:
      context: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always

  api:
    build:
      context: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.20.0.1"
    ipam:
      config:
        - subnet: "172.20.0.0/16"

volumes:
  pg_data: