version: '3.8'

services:
  db:
    build:
      context: db
      network: host
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5555"
    restart: always

  api:
    build:
      context: api
      network: host
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always


networks:
  app-network:


volumes:
  pg_data: