version: '3.8'

services:
  api:
    network_mode: host
    build:
      context: api
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
    ports:
      - "8000:8000"
    restart: always


volumes:
  pg_data:
