\set SENSOR_DB_USER `:SQL_USER`
\set SENSOR_DB_USER_PASSWORD `:SQL_PASSWORD`
\set SENSOR_DB_NAME `:SQL_DATABASE`

CREATE USER :SENSOR_DB_USER WITH PASSWORD ':SENSOR_DB_USER_PASSWORD';
CREATE DATABASE :SENSOR_DB_NAME OWNER :SENSOR_DB_USER;